modLoader = "javafml"
loaderVersion = "[37,38)"
license = "${license_name}"
issueTrackerURL = "${github_url}/issues"
showAsResourcePack = false

[[mods]]
modId = "annotateddi"
version = "${version}"
displayName = "${readable_name}"
updateJSONURL = "${forge_update_json_url}"
displayURL = "${modrinth_url}"
logoFile = "${logo_filename}"
credits = ""
authors = "The_Fireplace"
description = "${mod_description}"

[[dependencies.annotateddi]]
modId = "forge"
mandatory = true
versionRange = "[37,38)"
ordering = "NONE"
side = "BOTH"

[[dependencies.annotateddi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.18)"
ordering = "NONE"
side = "BOTH"