//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'java'
}
base.archivesName = "${archives_base_name}-Fabric-Processor"

dependencies {
    compileOnly group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "com.google.code.gson:gson:${project.gson_version}"
    implementation "com.google.auto.service:auto-service-annotations:${project.autoservice_version}"
    annotationProcessor "com.google.auto.service:auto-service:${project.autoservice_version}"

    compileOnly project(":processor")
}

tasks.register('processMainSource', Sync) {
    from sourceSets.main.java
    from project(':processor').sourceSets.main.java
    expand 'version': project.version
    into layout.buildDirectory.dir("src")
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier.set('sources')
    from project(':processor').sourceSets.main.allSource
    from sourceSets.main.allSource
}

javadoc {
    source project(':processor').sourceSets.main.allJava
    source sourceSets.main.allJava
}

java {
    withSourcesJar()
    withJavadocJar()
}

compileJava {
    source = processMainSource.outputs
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            def pub=it
            from components.java
            groupId project.maven_group
            project.afterEvaluate {
                pub.artifactId = base.archivesName.get()
            }
            version project.version
            pom {
                name = project.readable_name
                packaging = 'jar'
                description = project.maven_description
                url = project.modrinth_url
                scm {
                    connection = "scm:svn:${project.github_url}.git"
                    developerConnection = "scm:svn:${project.github_url}.git"
                    url = project.github_url
                }

                licenses {
                    license {
                        name = project.license_name
                        url = project.license_url
                    }
                }

                developers {
                    developer {
                        id = 'the_fireplace'
                        name = 'The_Fireplace'
                        email = 'git@the-fireplace.dev'
                    }
                }
            }
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir('staging-deploy')
        }
    }
}

afterEvaluate {
    def publishTask = tasks.find { it.name == 'publish' }
    if (publishTask) {
        publishTask.finalizedBy(copyArtifacts)
    }
}